sudo: false
matrix:
  include:
    - language: node_js
      node_js: 6.9
      os: linux
    - language: node_js
      node_js: 6.9
      os: osx
install:
  - npm install
script:
  - python start.py
