sudo: false
matrix:
  include:
    - language: node_js
      node_js: 6.9
      os: linux
    - language: node_js
      node_js: 6.9
      os: osx
install:
  - npm install
script:
  - cp index.js node_modules/karma-firefox-launcher/index.js
  - python start.py
